apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: atvt
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
